name: fonts
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.7.2=h06a4308_0
  - expat=2.6.2=h6a678d5_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.14=h5eee18b_0
  - pip=24.0=py312h06a4308_0
  - python=3.12.4=h5148396_1
  - readline=8.2=h5eee18b_0
  - setuptools=72.1.0=py312h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.43.0=py312h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==0.30.1
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - attrs==24.2.0
      - cachetools==5.5.0
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - coloredlogs==15.0.1
      - contourpy==1.2.1
      - cycler==0.12.1
      - datasets==2.21.0
      - deepspeed==0.14.4
      - diffusers==0.30.0
      - dill==0.3.8
      - einops==0.8.0
      - filelock==3.15.4
      - flatbuffers==24.3.25
      - fonttools==4.53.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - hjson==3.1.0
      - huggingface-hub==0.24.5
      - humanfriendly==10.0
      - idna==3.7
      - importlib-metadata==8.2.0
      - jinja2==3.1.4
      - kiwisolver==1.4.5
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - networkx==3.3
      - ninja==1.11.1.1
      - numpy==1.26.4
      - nvitop==1.3.2
      - omegaconf==2.3.0
      - onnxruntime==1.19.0
      - opencv-python==4.10.0.84
      - optimum-quanto==0.2.4
      - packaging==24.1
      - pandas==2.2.2
      - pillow==10.4.0
      - protobuf==5.27.3
      - psutil==6.0.0
      - py-cpuinfo==9.0.0
      - pyarrow==17.0.0
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pyparsing==3.1.3
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.2
      - regex==2024.7.24
      - requests==2.32.3
      - safetensors==0.4.4
      - sentencepiece==0.2.0
      - six==1.16.0
      - sympy==1.13.2
      - termcolor==2.4.0
      - timm==1.0.9
      - tokenizers==0.19.1
      - torch==2.4.0
      - torchvision==0.19.0
      - transformers==4.43.3
      - triton==3.0.0
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - urllib3==2.2.2
      - xxhash==3.5.0
      - yarl==1.9.4
      - zipp==3.20.0
